Repository baobabsoluciones/cornflow, pull requests merged in 2021-12, with the labels that each got.

#159 Added roles property to users
  cornflow/models/user.py
  cornflow/shared/authentication.py
  cornflow/tests/custom_test_case.py
  cornflow/tests/unit/test_roles.py
  cornflow/tests/unit/test_users.py
Labels: enhancement

#158 Docs
  docs/source/guides/coding_style.rst
  docs/source/guides/jsonschema.rst
Labels: documentation

#167 Bump airflow version to 2.2.0
  airflow_config/Dockerfile
Labels: enhancement

#168 Feature/bump airflow version
  airflow_config/Dockerfile
Labels: enhancement

#172 Password and email pattern validation
  cornflow/endpoints/signup.py
  cornflow/endpoints/user.py
  cornflow/models/user.py
  cornflow/tests/custom_liveServer.py
  cornflow/tests/custom_test_case.py
  cornflow/tests/integration/test_cornflowclient.py
  cornflow/tests/ldap/test_ldap_authentication.py
  cornflow/tests/unit/test_commands.py
  cornflow/tests/unit/test_log_in.py
  cornflow/tests/unit/test_roles.py
  cornflow/tests/unit/test_sign_up.py
  cornflow/tests/unit/test_users.py
Labels: enhancement

#170 Control DAG level permissions on cornflow
  .github/workflows/run_tests_airflow.yml
  airflow_config/dags/model_functions.py
  airflow_config/dags/optim_dag.py
  cornflow/app.py
  cornflow/commands/actions.py
  cornflow/commands/dag.py
  cornflow/commands/permissions.py
  cornflow/commands/roles.py
  cornflow/commands/schemas.py
  cornflow/commands/views.py
  cornflow/config.py
  cornflow/endpoints/case.py
  cornflow/endpoints/execution.py
  cornflow/endpoints/instance.py
  cornflow/endpoints/login.py
  cornflow/endpoints/signup.py
  cornflow/models/__init__.py
  cornflow/models/dag.py
  cornflow/models/permission.py
  cornflow/models/user.py
  cornflow/schemas/case.py
  cornflow/schemas/execution.py
  cornflow/schemas/instance.py
  cornflow/shared/authentication.py
  cornflow/tests/custom_liveServer.py
  cornflow/tests/custom_test_case.py
  cornflow/tests/data/full_case_patch.json
  cornflow/tests/data/json_patch_bad.json
  cornflow/tests/data/json_patch_good.json
  cornflow/tests/data/new_instance_2.json
  cornflow/tests/integration/test_cornflowclient.py
  cornflow/tests/unit/test_cases.py
  cornflow/tests/unit/test_log_in.py
  cornflow/tests/unit/test_users.py
  init_cornflow_service.py
  migrations/versions/f3bee20314a2_.py
  requirements.txt
Labels: enhancement, major change

#179 Feature/add missing tests
  cornflow/app.py
  cornflow/commands/permissions.py
  cornflow/endpoints/case.py
  cornflow/endpoints/execution.py
  cornflow/models/permission.py
  cornflow/schemas/case.py
  cornflow/schemas/execution.py
  cornflow/schemas/instance.py
  cornflow/tests/custom_liveServer.py
  cornflow/tests/custom_test_case.py
  cornflow/tests/data/full_case_patch.json
  cornflow/tests/data/json_patch_good.json
  cornflow/tests/integration/test_commands.py
  cornflow/tests/integration/test_cornflowclient.py
  cornflow/tests/unit/test_cases.py
  cornflow/tests/unit/test_commands.py
  cornflow/tests/unit/test_permissions.py
Labels: enhancement

#183 Feature/dag endpoints
  cornflow/endpoints/schemas.py
  cornflow/tests/custom_liveServer.py
  cornflow/tests/integration/test_cornflowclient.py
  cornflow/tests/unit/test_schemas.py
Labels: enhancement

#184 Added base user command, added to app and added covering tests
  cornflow/app.py
  cornflow/commands/users.py
  cornflow/tests/unit/test_commands.py
Labels: enhancement

#185 Added test to cascade operations
  cornflow/models/dag.py
  cornflow/models/user.py
  cornflow/tests/unit/test_dags.py
  cornflow/tests/unit/test_users.py
Labels: enhancement
