Repository baobabsoluciones/cornflow, pull requests merged in 2022-02, with the labels that each got.

#210 Database session management
  cornflow/commands/actions.py
  cornflow/commands/dag.py
  cornflow/commands/permissions.py
  cornflow/commands/roles.py
  cornflow/commands/views.py
  cornflow/endpoints/login.py
  cornflow/endpoints/user.py
  cornflow/models/case.py
  cornflow/models/meta_model.py
  cornflow/models/user.py
Labels: enhancement

#211 Test on action
  .github/workflows/run_tests_airflow.yml
  airflow_config/dags/README.rst
  airflow_config/dags/dag_timer.py
  airflow_config/dags/model_functions.py
  airflow_config/dags/optim_dag.py
  airflow_config/dags/update_all_schemas_v1.0.py
  cornflow/endpoints/dag.py
  cornflow/models/execution.py
  cornflow/shared/const.py
  cornflow/tests/const.py
  cornflow/tests/integration/test_commands.py
  cornflow/tests/integration/test_cornflowclient.py
Labels: enhancement

#213 Feature/check solution save
  cornflow/endpoints/__init__.py
  cornflow/endpoints/case.py
  cornflow/endpoints/dag.py
  cornflow/endpoints/execution.py
  cornflow/endpoints/instance.py
  cornflow/models/case.py
  cornflow/models/meta_model.py
  cornflow/schemas/case.py
  cornflow/schemas/execution.py
  cornflow/schemas/instance.py
  cornflow/tests/integration/test_cornflowclient.py
  cornflow/tests/unit/test_cases.py
  cornflow/tests/unit/test_instances.py
  migrations/versions/00757b557b02_.py
Labels: enhancement

#208 Feature/gurobi optimizer installation
  airflow_config/Dockerfile
  airflow_config/scripts/init_airflow_service.py
  airflow_config/scripts/solver_installation.py
  airflow_config/scripts/solvers/get_gurobi.py
  airflow_config/webserver_ldap.py
  docker-compose-airflow-celery-separate.yml
  docker-compose-cornflow-celery.yml
  docker-compose-cornflow-separate.yml
  docker-compose.yml
  docs/source/deploy/access.rst
  init_cornflow_service.py
Labels: enhancement, cornflow-server

#222 Feature/test client
  cornflow/app.py
  cornflow/commands/users.py
  cornflow/config.py
  cornflow/endpoints/instance.py
Labels: bug, cornflow-server, cornflow-client

#226 Removed MIPCL from available solvers list
  airflow_config/scripts/solver_installation.py
Labels: bug
