Repository baobabsoluciones/cornflow, pull requests merged in 2023-03, with the labels that each got.

#389 Feature/s7 auto script
  cornflow-dags/DAG/auto_scripts/automatic_scripts.py
  cornflow-dags/DAG/auto_scripts/executed_scripts/README.rst
  cornflow-dags/DAG/auto_scripts/scripts_to_execute/README.rst
  cornflow-dags/tests/data/auto_scripts/auto_scripts_dag_dummy.py
  cornflow-dags/tests/test_dags_af.py
Labels: enhancement, server, dags

#397 Fixed alembic version to 1.9.2
  cornflow-server/requirements.txt
Labels: bug

#400 Feature/development coverage
  .github/workflows/test_cornflow_client.yml
  .github/workflows/test_cornflow_core.yml
  .github/workflows/test_cornflow_dags.yml
  .github/workflows/test_cornflow_server.yml
Labels: bug

#399 Added the indicators to the rostering DAG
  cornflow-dags/DAG/rostering/core/experiment.py
  cornflow-dags/DAG/rostering/schemas/solution.json
Labels: enhancement

#406 Added default_args toa ctivate_dags
  cornflow-dags/DAG/activate_dags.py
Labels: enhancement

#413 Feature/cleanup
  cornflow-dags/DAG/dag_timer.py
  cornflow-dags/DAG/update_all_schemas.py
  cornflow-dags/DAG/update_dag_registry.py
  cornflow-dags/examples/dag_tests_cornflow.py
  cornflow-dags/tests/test_dags_af.py
Labels: bug

#417 Changes from PR
  cornflow-dags/DAG/rostering/core/instance.py
  cornflow-dags/tests/test_dags_af.py
Labels: enhancement

#371 Feature/package
  .github/workflows/cornflow-publish-to-pypi.yml
  cornflow-server/Dockerfile
  cornflow-server/MANIFEST.in
  cornflow-server/README.rst
  cornflow-server/cornflow/app.py
  cornflow-server/cornflow/cli/__init__.py
  cornflow-server/cornflow/cli/actions.py
  cornflow-server/cornflow/cli/arguments.py
  cornflow-server/cornflow/cli/config.py
  cornflow-server/cornflow/cli/migrations.py
  cornflow-server/cornflow/cli/permissions.py
  cornflow-server/cornflow/cli/roles.py
  cornflow-server/cornflow/cli/service.py
  cornflow-server/cornflow/cli/users.py
  cornflow-server/cornflow/cli/utils.py
  cornflow-server/cornflow/cli/views.py
  cornflow-server/cornflow/commands/__init__.py
  cornflow-server/cornflow/commands/access.py
  cornflow-server/cornflow/commands/permissions.py
  cornflow-server/cornflow/commands/views.py
  cornflow-server/cornflow/endpoints/__init__.py
  cornflow-server/cornflow/external_app/README.rst
  cornflow-server/cornflow/external_app/endpoint/__init__.py
  cornflow-server/cornflow/external_app/model/__init__.py
  cornflow-server/cornflow/external_app/schemas/__init__.py
  cornflow-server/cornflow/migrations/README
  cornflow-server/cornflow/migrations/alembic.ini
  cornflow-server/cornflow/migrations/env.py
  cornflow-server/cornflow/migrations/script.py.mako
  cornflow-server/cornflow/migrations/versions/00757b557b02_.py
  cornflow-server/cornflow/migrations/versions/1af47a419bbd_.py
  cornflow-server/cornflow/migrations/versions/4aac5e0c6e66_.py
  cornflow-server/cornflow/migrations/versions/7c3ea5ab5501_.py
  cornflow-server/cornflow/migrations/versions/a472b5ad50b7_.py
  cornflow-server/cornflow/migrations/versions/c2db9409cb5f_.py
  cornflow-server/cornflow/migrations/versions/c8a6c762e818_.py
  cornflow-server/cornflow/migrations/versions/ca449af8034c_.py
  cornflow-server/cornflow/migrations/versions/d0e0700dcd8e_.py
  cornflow-server/cornflow/migrations/versions/d1b5be1f0549_.py
  cornflow-server/cornflow/migrations/versions/e1a50dae1ac9_.py
  cornflow-server/cornflow/migrations/versions/e937a5234ce4_.py
  cornflow-server/cornflow/migrations/versions/f3bee20314a2_.py
  cornflow-server/cornflow/shared/__init__.py
  cornflow-server/cornflow/tests/unit/test_cli.py
  cornflow-server/cornflow/tests/unit/test_sign_up.py
  cornflow-server/cornflow/tests/unit/test_tables.py
  cornflow-server/cornflow/tests/unit/test_token.py
  cornflow-server/init_cornflow_service.py
  cornflow-server/migrations/versions/7c3ea5ab5501_.py
  cornflow-server/setup.py
Labels: enhancement, server

#422 Updated workflow
  .github/workflows/cornflow-publish-to-pypi.yml
Labels: bug

#425 Development
  .github/workflows/cornflow-publish-to-pypi.yml
  .github/workflows/test_cornflow_client.yml
  cornflow-dags/DAG/activate_dags.py
  cornflow-server/Dockerfile
  cornflow-server/changelog.rst
  cornflow-server/cornflow/commands/actions.py
  cornflow-server/requirements.txt
  cornflow-server/setup.py
  libs/client/cornflow_client/core/application.py
  libs/client/setup.py
Labels: enhancement, server, client, dags

#429 Hotfix
  .github/workflows/cornflow-publish-to-pypi.yml
  .github/workflows/test_cornflow_client.yml
  cornflow-server/Dockerfile
  cornflow-server/cornflow/app.py
  cornflow-server/cornflow/cli/service.py
  cornflow-server/cornflow/endpoints/health.py
  cornflow-server/cornflow/tests/custom_liveServer.py
  cornflow-server/cornflow/tests/unit/test_health.py
  cornflow-server/requirements.txt
  cornflow-server/setup.py
  libs/client/cornflow_client/airflow/api.py
  libs/client/setup.py
Labels: bug

#428 Feature/test extra args
  cornflow-dags/DAG/rostering/__init__.py
Labels: enhancement, dags

#431 Development
  .github/workflows/cornflow-publish-to-pypi.yml
  .github/workflows/test_cornflow_client.yml
  cornflow-dags/DAG/rostering/__init__.py
  cornflow-server/Dockerfile
  cornflow-server/changelog.rst
  cornflow-server/cornflow/app.py
  cornflow-server/cornflow/cli/service.py
  cornflow-server/cornflow/endpoints/health.py
  cornflow-server/cornflow/tests/custom_liveServer.py
  cornflow-server/cornflow/tests/unit/test_health.py
  cornflow-server/requirements.txt
  cornflow-server/setup.py
  libs/client/changelog.rst
  libs/client/cornflow_client/airflow/api.py
  libs/client/setup.py
Labels: bug, enhancement, server, client

#433 Feature/local dev (#432)
  cornflow-server/Dockerfile
  cornflow-server/cornflow/__init__.py
  cornflow-server/cornflow/app.py
  cornflow-server/cornflow/cli/service.py
  cornflow-server/cornflow/cli/utils.py
  cornflow-server/cornflow/tests/integration/post_deployment_check.py
  cornflow-server/cornflow/tests/integration/test_cornflowclient.py
  cornflow-server/cornflow/tests/unit/test_cli.py
  cornflow-server/cornflow/tests/unit/test_commands.py
  cornflow-server/cornflow/tests/unit/test_example_data.py
  cornflow-server/setup.py
Labels: enhancement, server
