Repository baobabsoluciones/cornflow, pull requests merged in 2025-03, with the labels that each got.

#605 Feature/issue 569
  libs/client/cornflow_client/core/experiment.py
  libs/client/cornflow_client/tests/unit/test_instance_solution_methods.py
Labels: enhancement

#611 Fixed probable error on offset filter
  cornflow-server/cornflow/models/base_data_model.py
  cornflow-server/cornflow/models/meta_models.py
  cornflow-server/cornflow/schemas/query.py
  cornflow-server/cornflow/tests/custom_test_case.py
  cornflow-server/cornflow/tests/unit/test_apiview.py
  cornflow-server/cornflow/tests/unit/test_log_in.py
  cornflow-server/cornflow/tests/unit/test_roles.py
  cornflow-server/cornflow/tests/unit/test_users.py
Labels: bug

#571 add a class to check the instance or solution.
  .github/workflows/test_cornflow_dags.yml
  cornflow-dags/DAG/bar_cutting/core/experiment.py
  cornflow-dags/DAG/bar_cutting/core/instance.py
  cornflow-dags/DAG/facility_location/core/experiment.py
  cornflow-dags/DAG/facility_location/core/instance.py
  cornflow-dags/DAG/graph_coloring/core/experiment.py
  cornflow-dags/DAG/graph_coloring/core/instance.py
  cornflow-dags/DAG/knapsack/core/experiment.py
  cornflow-dags/DAG/knapsack/core/instance.py
  cornflow-dags/DAG/roadef/core/experiment.py
  cornflow-dags/DAG/roadef/core/instance.py
  cornflow-dags/DAG/roadef/solvers/MIPModel.py
  cornflow-dags/DAG/roadef/solvers/PeriodicMIP.py
  cornflow-dags/DAG/rostering/__init__.py
  cornflow-dags/DAG/rostering/core/experiment.py
  cornflow-dags/DAG/rostering/core/instance.py
  cornflow-dags/DAG/rostering/data/test_instance_bad_timeslot_length.json
  cornflow-dags/DAG/rostering/schemas/instance_checks.json
  cornflow-dags/DAG/rostering/schemas/solution_checks.json
  cornflow-dags/DAG/solve_model_dag/__init__.py
  cornflow-dags/DAG/tsp/core/experiment.py
  cornflow-dags/DAG/tsp/core/instance.py
  cornflow-dags/DAG/two_dimension_bin_packing/__init__.py
  cornflow-dags/DAG/two_dimension_bin_packing/core/instance.py
  cornflow-dags/DAG/two_dimension_bin_packing/schemas/config.json
  cornflow-dags/DAG/two_dimension_bin_packing/schemas/instance_checks.json
  cornflow-dags/DAG/vrp/core/experiment.py
  cornflow-dags/DAG/vrp/core/instance.py
  cornflow-dags/requirements.txt
  cornflow-dags/tests/integration/__init__.py
  cornflow-dags/tests/integration/test_dags_af.py
  cornflow-dags/tests/unit/__init__.py
  cornflow-dags/tests/unit/test_dags.py
  cornflow-dags/tests/unit/test_rostering.py
  libs/client/cornflow_client/constants.py
  libs/client/cornflow_client/core/application.py
  libs/client/cornflow_client/core/experiment.py
  libs/client/cornflow_client/core/instance.py
  libs/client/cornflow_client/tests/unit/test_core.py
Labels: enhancement

#612 Feature/utc
  cornflow-dags/DAG/run_deployed_dags.py
  cornflow-dags/DAG/two_dimension_bin_packing/core/instance.py
  cornflow-server/cornflow/endpoints/login.py
  cornflow-server/cornflow/models/meta_models.py
  cornflow-server/cornflow/models/user.py
  cornflow-server/cornflow/schemas/user.py
  cornflow-server/cornflow/shared/authentication/auth.py
  cornflow-server/cornflow/tests/custom_test_case.py
  cornflow-server/cornflow/tests/unit/test_users.py
Labels: enhancement

#574 Bugfix/review commands
  cornflow-server/Dockerfile
  cornflow-server/cornflow/cli/migrations.py
  cornflow-server/cornflow/cli/service.py
  cornflow-server/cornflow/cli/utils.py
Labels: server
